
export const FETCH_FANS_START = 'FETCH_FANS_START';
export const FETCH_FANS_SUCCESS = 'FETCH_FANS_SUCCESS';
export const FETCH_FANS_FAIL = 'FETCH_FANS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_ALREADY = 'AUTH_ALREADY';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';